config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => "homes#about"
    resources :addresses
    resources :orders do
      post 'order/confirm' => 'orders#confirm'
      get 'orders/complete' => 'orders#complete'
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
    end
    resources :items
    get 'customers/mypage' => 'customers#show'
    get 'customers/mypage/edit' => 'customers#edit'
    patch 'customers/mypage' =>  'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
  end
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
   '〒' + self.post_number + ' ' + self.address + ' ' + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many:items
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_one_attached :item_image

  
  validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  has_many :order_items

  def get_item_image
    (item_image.attached?) ? item_image : "no_image.jpg"
  end

  def with_tax_price
      (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  has_many :customer_orders, dependent: :destroy
  belongs_to :customer

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { "wait_payment": 0, "confirm_payment": 1, "making": 2, "preparing_ship": 3, "finish_prepare": 4}

  def with_tax_price
      (price * 1.1).floor
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, dependent: :destroy
  belongs_to :item

  enum making_status: { impossible_making: 0, waiting_for_making: 1, making: 2, complete: 3 }

  def with_tax_price
      (price * 1.1).floor
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_number, :phone_number, :address, :email, :is_valid)
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

private

  def genre_params
     params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  def destroy
    @items = Item.all
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path(@item.id)

  end

  private
  
  def item_params
    params.require(:item).permit(:genre_id, :name, :item_image, :introduction, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def create
    @order = Order.new(order_params)
    @order.save
  end

  def new
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params) && @order.order_status == "confirm_payment"
       flash[:notice] = "注文ステータス更新"
       @order.order_details.update_all(making_status: 1)
       redirect_to admin_order_path(@order.id)
    else
       redirect_to admin_order_path(@order.id)
    end
  end



  private
    def order_params
      params.require(:order).permit(:customer_id, :post_number, :address, :name, :shipping_cost, :total_payment, :payment_method, :order_status, :amount)
    end
    
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
  
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/_show.html.erb
<div class='row'>
  <div class='col-md-8 offset-2'>
    <h3 class="my-4 mt-5"><%= customer.last_name %><%= customer.first_name %>さんの会員詳細</h3>
    <table class="table">
      <thead>
        <tr>
          <th>会員ID</th>
          <td><%= customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= customer.last_name %><%= customer.first_name %></td>
          </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= customer.last_name_kana %><%= customer.first_name_kana %></td>
          </tr>
        <tr>
        <th>郵便番号</th>
          <td><%= customer.post_number %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= customer.phone_number %></td>
       </tr>
       <tr>
          <th>メールアドレス</th>
          <td><%= customer.email %></td>
       </tr>
       <tr>
        <th>会員ステータス</th>
      <% if customer.is_valid == '有効'  %>
        <th class = "text-success">
        <%= customer.is_valid %>
        </th>
      <%else%>
        <th class = "text-danger">
        <%= customer.is_valid %>
        </th>
      <% end %>
      </tr>
    </thead>
    </table>
  </div>
</div>

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <h3 class="my-4 mt-5"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h3>

      <%= form_with model: @customer,url: admin_customer_path, method: :patch, local:true do |f| %>
      <table class='table table-hover'>
    	  <th>会員ID</th>
    	  <th><%= @customer.id %></th>
            <tr class="form-group">
              <th><%= f.label :"氏名"%></th>
              <th><%= f.text_field :last_name,autofocus: true ,class: "form-control last_name" %></th>
              <th><%= f.text_field :first_name,autofocus: true ,class: "form-control first_name" %></th>
            </tr>
          <tr class="form-group">
            <th><%= f.label :"フリガナ"%></th>
            <th><%= f.text_field :last_name_kana,autofocus: true, class: "form-control last_name_kana" %></th>
            <th><%= f.text_field :first_name_kana,autofocus: true, class: "form-control first_name_kana" %></th>
          </tr>
          <tr class="form-group">
            <th><%= f.label :"郵便番号"%></th>
            <th><%= f.text_area :post_number,autofocus: true, class: "form-control customer.post_number" %></th>
          </tr>
          <tr class="form-group">
            <th><%= f.label :"住所"%></th>
            <th><%= f.text_area :address,autofocus: true, class: "form-control customer.address" %></th>
          </tr>
          <tr class="form-group">
            <th><%= f.label :"電話番号"%></th>
            <th><%= f.text_area :phone_number,autofocus: true, class: "form-control customer.phone_number" %></th>
          </tr>
          <tr class="form-group">
            <th><%= f.label :"メールアドレス"%></th>
            <th><%= f.email_field :email,autofocus: true, class: "form-control customer.email" %></th>
          </tr>
          <tr class="form-group">
            <th><%= f.label :"会員ステータス"%></th>
            <th>
              <%= f.radio_button :is_valid, '有効' %>
              <%= f.label :is_valid, '有効' %>
            </th>
            <th>
              <%= f.radio_button :is_valid, '退会' %>
              <%= f.label :is_valid, '退会' %>
            </th>
          </tr>
          <tr class="form-group">
            <th></th>
            <th><%= f.submit "変更する", class: 'btn btn-success' %></th>
          </tr>
      </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-8 offset-2'>
      <h3 class="my-4 mt-5">会員一覧</h3>

      <table class="table table">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |user| %>
            <tr>
              <td>
                <%= user.id %>
              </td>
              <td>
              <%= link_to admin_customer_path(user) do%>
                <%= user.last_name %><%= user.first_name %>
              <% end %>
              </td>
              <td><%= user.email%></td>
              <% if user.is_valid == '有効'  %>
          	    <th class = "text-success">
          	      <%= user.is_valid %>
          	    </th>
          	  <%else%>
          	    <th class = "text-danger">
          	      <%= user.is_valid %>
          	    </th>
          	  <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
        <p><%= paginate @customers %></p>
    </div>
  </div>

app/views/admin/customers/show.html.erb
<div class ="container">
   <%= render 'show' ,customer: @customer %>
  <div class="text-center">
    <table class="table">
      <th><%= link_to '編集する', edit_admin_customer_path(@customer), class: "btn btn-sm btn-success" %></th>
      <th><%= link_to '注文履歴一覧を見る', admin_root_path, class: "btn btn-sm btn-primary" %></th>
    </table>
  </div>
</div>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <h3 class="my-4 mt-5">ジャンル編集</h3>

      <%= form_with model: @genre, url: admin_genre_path,method: :patch do |f| %>

      <div class="text-center my-4 mt-5">
        <td><%= f.label :"ジャンル名", class: "mr-3" %></td>
        <td><%= f.text_field :name, class: "mr-5" %></td>
        <td><%= f.submit "変更を保存", class: "btn btn-primary" %></td>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <h3 class="my-4 mt-5">ジャンル一覧・追加</h3>

      <%=form_with model: @genre,url: admin_genres_path, method: :post do |f| %>

      <div class="text-center my-4 mt-5">
        <td><%= f.label :"ジャンル名", class: "mr-3" %></td>
        <td><%= f.text_field :name, class: "mr-5" %></td>
        <td><%= f.submit'新規登録',class: "btn btn-primary" %></td>
      </div>

      <% end %>

      <div class="text-center my-4 mt-5">
        <table class="table table-hover">
          <thead>
            <th>ジャンル</th>
          </thead>
        <% @genres.each do |genre| %>
          <td><%= genre.name %></td>
          <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %></td>
         </tbody>
        <%end%>
      </div>
    </div>
  </div>
</dvi>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <h3 class="my-4 mt-5">商品編集</h3>

      
      <%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true do |f| %>

        <div class="field text-center mt-4">
        <%= f.label :"商品画像" %>
        <%= f.file_field :item_image, accept: "image/*" %>
        </div>
        
        <div class="field text-center mt-4">
        <%= f.label :"商品名", class: "mr-3" %>
        <%= f.text_field :name %>
        </div>
        
        <div class="field text-center mt-4">
        <%= f.label :"商品説明", class: "mr-3" %>
        <%= f.text_area :introduction %>
        </div>
        
        <div class="field text-center mt-4">
        <%= f.label :"ジャンル", class: "mr-3" %>
        <%= f.collection_select :genre_id, Genre.all, :id, :name %>
        </div>
        
        <div class="field text-center mt-4">
        <%= f.label :"税抜価格", class: "mr-3" %>
        <%= f.text_field :price %>円
        </div>
        
        <div class="field text-center mt-4">
        <%= f.label :"販売ステータス", class: "mr-3" %>
        <%= f.radio_button :is_active, true %>
        <%= f.label :販売中 %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :販売停止中 %>
        </div>
        
        <div class="actions text-center mt-4">
        <%= f.submit "変更を保存", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <h3 class="my-4 mt-5">商品一覧</h3>

      <%= link_to new_admin_item_path, style:"font-size: 35px;" do %>
        <i class="fas fa-plus-circle"></i>
      <% end %>

      <table class="table table-hover">
        <thead>
          <tr>
            <th>商品ID</th>
            <th>商品名</th>
            <th>税抜価格</th>
            <th>ジャンル</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td>
              <%= link_to admin_item_path(item.id) do %>
              <%= item.name %>
              <% end %>
            </td>
            <td><%= number_to_currency(item.price, unit: "¥", format: "%u %n" ) %></td>
            <td><%= item.genre.name %></td>
            <th>
              <% if item.is_active == true %>
              <p class = "text-success">
                販売中
              </p>
              <% else %>
              <p class = "text-danger">
                販売停止中
              </p>
              <% end %>
            </th>
          </tr>
          <% end %>
        </tbody>
      </table>
        <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-3">
      <h3 class="my-4 mt-5">商品新規登録</h3>

      <%= form_with model: @item, url: admin_items_path, method: :post, local: true do |f| %>

       <table class="table table-borderless table-sm">
        <div class="field">
          <tr>
            <td><%= f.label :"商品画像" %></td>
            <td><%= f.file_field :item_image, accept: "image/*" %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
            <td><%= f.label :"商品名", class: "mr-3"%></td>
            <td><%= f.text_field :name %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
            <td><%= f.label :"商品説明", class: "mr-3" %></td>
            <td><%= f.text_area :introduction %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
            <td><%= f.label :"ジャンル" %></td>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
          </tr>
        </div>

        <div class="field">
          <tr>
            <td><%= f.label :"税抜価格", class: "mr-3" %></td>
            <td><%= f.text_field :price %>円</td>
          </tr>
        </div>

        <div class="field">
          <%= f.label :"販売ステータス" %>
          <%= f.radio_button :is_active, true %>
          <%= f.label :is_active, "販売中", value: true %>
          <%= f.radio_button :is_active, false %>
          <%= f.label  :is_active, "販売停止中", value: false %>
        </div>

        <div class="actions">
          <td></td>
            <td><%= f.submit "新規登録",class: "btn btn-success px-5 mt-4" %></td>
        </div>
       </table>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 offset-2">
      <h3 class="my-4 mt-5">商品詳細</h3>

      <div class="text-center">
        <%= image_tag @item.get_item_image, size: "350x220" %>
      </div>


      <div class="text-center">
        <br>
        <table class="table">
          <tr>
            <th>商品名</th>
            <td><%= @item.name %></td>
          </tr>

          <tr>
            <th>商品説明</th>
            <td><%= @item.introduction %></td>
          </tr>

          <tr>
            <th>ジャンル</th>
            <td><%= @item.genre.name %></td>
          </tr>

          <tr>
            <th> 税込価格<br>(税抜価格)</th>
            <td><%= @item.with_tax_price.to_s(:delimited) %>(<%= @item.price.to_s(:delimited) %>)円</td>
          </tr>

          <tr>
            <th>販売ステータス</th>
            <th>
              <% if @item.is_active == true %>
              <p class = "text-success">
                販売中
              </p>
              <% else %>
              <p class = "text-danger">
                販売停止中
              </p>
              <% end %>
            </th>
          </tr>
        </table>
      </div>

       <div class="text-center">
        <table class="table">
          <th><%= link_to "編集する", edit_admin_item_path(@item), class: 'btn btn-success' %></th>
          <th><%= link_to "削除する", admin_item_path(@item), method: :delete, data: {confirm:  "本当に削除しますか？"}, class: "btn btn-danger" %></th>
        </table>
       </div>
    </div>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class='container'>
  <h3>注文履歴一覧</h3>
  <div class ='row'>
    <div class = "border table-striped table table-hover">
      <table class = "col-md-12">
          <thead>
            <tr>
              <th>購入日時</th>
              <th>購入者</th>
              <th>注文個数</th>
              <th>注文ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @orders.each do |order| %>
            <tr>
              <td><%= link_to admin_order_path(order.id) do %>
                  <%= l order.created_at %>
                  <% end %>
              </td>
              <td><%= order.name %></td>
              <td>
                <% @amount_sum = 0 %>
                <% order.order_details.each do |detail| %>
                <% @amount_sum += detail.quantity %>
                <% end %>
                <%= @amount_sum %>
              </td>
              <td><%= order.order_status_i18n %></td>
            </tr>
            <% end %>
          </tbody>
      </table>
    </div>
    <div>
       <%= paginate @orders %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class='container'>
  <h3>注文履歴詳細</h3>
  <table>
   <tbody>
    <tr>
      <th>購入者</th>
      <td>
        <%= link_to admin_customer_path(@order.customer_id)  do %>
          <%= @order.customer.last_name %><%= @order.customer.first_name %>
        <% end %>
      </td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td>
        <p>〒<%= @order.post_number %></p>
        <p><%= @order.address %></p>
        <p><%= @order.name %></p>
      </td>
    </tr>
    <tr>
      <th>支払い方法</th>
      <td><%= @order.payment_method %><td>
    </tr>
    <tr>
      <th>注文ステータス</th>
      <td>
        <%= form_with(model: @order, url: admin_order_path(@order.id), method: :patch, local: true) do |f| %>
        <%= f.select :order_status, Order.order_statuses_i18n.invert, {prompt: false}, class: "order_status" %>
        <%= f.submit "更新" , class: "btn btn-success" %>
        <% end %>
      </td>
    </tr>
   </tbody>
  </table>
  <%= render "admin/order_details/index", order: @order %>
</div>