config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
      registrations: "public/registrations",
      sessions: 'public/sessions'
  }
  
  # 管理者用
  # URL /admin/sign_in ...
    devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
      sessions: "admin/sessions"
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items
    resources :genres
    resources :customers
    resources :orders
    resources :order_details
  end

  scope module: :public do
    root to: 'homes#top'
    get '/about' => "homes#about"
    resources :addresses
    resources :orders do
      post 'order/confirm' => 'orders#confirm'
      get 'orders/complete' => 'orders#complete'
    end
    resources :cart_items, only: [:index, :create, :update, :destroy] do
      delete 'cart_items/all_destroy' => 'cart_items#all_destroy'
    end
    resources :items
    get 'customers/mypage' => 'customers#show'
    get 'customers/mypage/edit' => 'customers#edit'
    patch 'customers/mypage' =>  'customers#update'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
  end
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
   '〒' + self.post_number + ' ' + self.address + ' ' + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many:items
end

app/models/item.rb
class Item < ApplicationRecord
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_one_attached :item_image

  
  validates :genre_id, presence: true
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  has_many :order_items

  def get_item_image
    (item_image.attached?) ? item_image : "no_image.jpg"
  end

  def with_tax_price
      (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details
  has_many :customer_orders, dependent: :destroy
  belongs_to :customer

  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { "wait_payment": 0, "confirm_payment": 1, "making": 2, "preparing_ship": 3, "finish_prepare": 4}

  def with_tax_price
      (price * 1.1).floor
  end

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order, dependent: :destroy
  belongs_to :item

  enum making_status: { impossible_making: 0, waiting_for_making: 1, making: 2, complete: 3 }

  def with_tax_price
      (price * 1.1).floor
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre=Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

private

  def genre_params
     params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item.id)
  end

  def destroy
    @items = Item.all
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path(@item.id)

  end

  private
  
  def item_params
    params.require(:item).permit(:genre_id, :name, :item_image, :introduction, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def create
    @order = Order.new(order_params)
    @order.save
  end

  def new
    @order = Order.new
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params) && @order.order_status == "confirm_payment"
       flash[:notice] = "注文ステータス更新"
       @order.order_details.update_all(making_status: 1)
       redirect_to admin_order_path(@order.id)
    else
       redirect_to admin_order_path(@order.id)
    end
  end



  private
    def order_params
      params.require(:order).permit(:customer_id, :post_number, :address, :name, :shipping_cost, :total_payment, :payment_method, :order_status, :amount)
    end
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<nav class = "navbar navbar-expand-lg navbar-light bg-light">
   <div class = "container">
      <a class="navbar-brand" href="/"><span>WAFFLE SUBURB</span></a><%= image_tag 'IMG_4883 2.JPG', style: "padding: 5px; width: auto; height:60px" %>
      <div class = "navbar-nav ml-5">
         <% if customer_signed_in? %>
            <li>
              ようこそ、<%= current_customer.last_name %>さん！
            </li>
         <% end %>
      </div>
      <script src="https://kit.fontawesome.com/801a1ac1e5.js" crossorigin="anonymous"></script>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
       <ul class="navbar-nav ml-auto">
          <% if customer_signed_in? %>
           <li>
             <%= link_to customers_mypage_path,class: 'btn' do%>
                <i class="fa-solid fa-user"></i>マイページ
             <% end %>
           </li>
           <li>
             <%= link_to items_path,class: 'btn' do%>
                <i class="fa-brands fa-shopify"></i>商品一覧
             <% end %>
           </li>
           <li>
             <%= link_to cart_items_path(current_customer),class: 'btn' do%>
                <i class="fa-solid fa-cart-shopping"></i>カート
             <% end %>
           </li>
           <li>
             <%= link_to destroy_customer_session_path, method: :delete,class: 'btn' do%>
                <i class="fas fa-sign-out-alt"></i>ログアウト
             <% end %>
              </li>
          <% elsif admin_signed_in? %>
           <li>
             <%= link_to admin_items_path,class: 'btn' do%>
                <i class="fa-brands fa-shopify"></i>商品一覧
             <% end %>
           </li>
           <li>
             <%= link_to admin_customers_path,class: 'btn' do%>
                <i class="fa-solid fa-user"></i>会員一覧
             <% end %>
           </li>
           <li>
             <%= link_to admin_root_path,class: 'btn' do%>
                 <i class="fa-brands fa-shopify"></i>注文履歴一覧
             <% end %>
           </li>
           <li>
             <%= link_to admin_genres_path,class: 'btn' do%>
                 <i class="fa-solid fa-tag"></i>ジャンル一覧
             <% end %>
           </li>
           <li>
             <%= link_to destroy_admin_session_path, method: :delete,class: 'btn' do%>
                <i class="fas fa-sign-out-alt"></i>ログアウト
             <% end %>
           </li>
          <% else %>
           <li>
             <%= link_to  about_path,class: 'btn' do%>
                 About
             <% end %>
           </li>
           <li>
             <%= link_to  items_path,class: 'btn' do%>
               <i class="fa-brands fa-shopify"></i>商品一覧
             <% end %>
           </li>
           <li>
             <%= link_to new_customer_registration_path,class: 'btn' do%>
                <i class="fas fa-user-plus"></i>新規登録
             <% end %>
           </li>
           <li>
             <%= link_to new_customer_session_path,class: 'btn ' do%>
                <i class="fas fa-sign-in-alt"></i>ログイン
             <% end %>
           </li>
          <% end %>
        </ul>
      </div>
   </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waffle</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= render "layouts/header"%>
    <%= yield %>
  </body>
</html>